rouge: pygments

# 作者信息
author:
  name: Hua
  email: 850360626@qq.com
  link: http://stuhua.github.io
  github: http://github.com/stuhua

# 站点信息
title: Hua的博客
description: Hua的博客
url: http://stuhua.github.io
language: 中文

#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
#analytics :
#  provider : custom

