highlighter: pygments

# 作者信息
author:
  name: Super Hua
  email: qq850360626@gmail.com
  link: http://tomhuahua.github.io
  weibo: http://weibo.com/superhua
  github: http://github.com/tomhuahua

# 站点信息
title: Super Hua的博客
description: Super Hua的博客
url: http://tomhuahua.github.io
language: 中文
